cart/urls.py
from django.urls import path

from cart.views import (
    add_to_cart_view,
    detail_cart_view,
    remove_from_cart_view,
    experiment
)

app_name = 'cart'

urlpatterns = [
    path('', detail_cart_view, name='detail_cart'),
    path('add/<int:product_id>', add_to_cart_view, name='add_to_cart'),
    path('remove/<int:product_id>', remove_from_cart_view, name='remove_from_cart'),
    path('experiment/', experiment, name='experiment'),
]

coupons/urls.py
from django.urls import path

from coupons.views import coupon_apply_view

app_name = 'coupons'

urlpatterns = [
    path('apply/', coupon_apply_view, name='apply'),
]

orders/urls.py
from django.urls import path

from orders.views import (
    create_order_view,
    create_order_done_view,
    admin_order_detail_view,
    admin_order_pdf_view,

)

app_name = 'orders'

urlpatterns = [

    path('create-order/', create_order_view, name='create_order'),
    path('create-order/<int:order_id>/', create_order_done_view, name='create_order_done'),
    path('admin/order/<int:order_id>/', admin_order_detail_view, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf_view, name='admin_order_pdf'),

]

shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('store.urls', namespace='store')),
]
if settings.DEBUG:
    urlpatterns += static(
        prefix=settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    # django-debug-toolbar
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

store/urls.py
from django.urls import path

from store.views import (
    experiment_view,
    list_product_view,
    detail_product_view,
)

app_name = 'store'

urlpatterns = [
    path('experiment/', experiment_view, name='experiment'),

    path('', list_product_view, name='list_products'),
    path('<slug:category_slug>/', list_product_view, name='list_products_by_category'),
    path('<int:pk>/<slug:slug>/', detail_product_view, name='detail_product'),

]

cart/forms.py
from django import forms


class AddToCartForm(forms.Form):
    QUANTITY_CHOICE = [(str(i), i) for i in range(1, 21)]

    quantity = forms.TypedChoiceField(
        choices=QUANTITY_CHOICE,
        coerce=int,
    )
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

# TypedChoiceField - тоже что и ChoiceField, только с имнованным аргументом coerce (принуждать)
# который будет менять тип данных из того что выбрали на тот который передаётся в coerce
# в шаблоне будет тег <select> с выбором options (варианты из QUANTITY_CHOICE)
# благодаря этому полю мы имеем в python коде когда достаём из request.POST
# цифру quantity как int
# https://docs.djangoproject.com/en/4.0/ref/forms/fields/#typedchoicefield
# https://github.com/Kirill67tyar/myshop/blob/master/src/cart/forms.py

cart/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from django.views.decorators.http import require_POST

from store.models import Product
from store.recommenders import Recommender
from cart.carts import Cart
from cart.forms import AddToCartForm
from coupons.forms import CouponApplyForm

from common.analizetools.analize import (
    p_dir, p_mro, p_glob, p_loc, p_type,
    delimiter, p_content, show_builtins,
    show_doc, console, console_compose,
)


@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request=request)
    product = get_object_or_404(
        klass=Product,
        pk=product_id
    )
    form = AddToCartForm(data=request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update'],
        )
    return redirect(to='cart:detail_cart')


def remove_from_cart_view(request, product_id):
    cart = Cart(request=request)
    product = get_object_or_404(
        klass=Product,
        pk=product_id
    )
    cart.remove(product)
    return redirect(to='cart:detail_cart')


def detail_cart_view(request):
    cart = Cart(request=request)
    products = []
    recommendations = None
    for item in cart:
        item['update_quantity_form'] = AddToCartForm(
            initial={
                'quantity': item['quantity'],
                'update': True,
            }
        )
        products.append(item['product'])  # для класса Recommender
    if cart.coupon:
        coupon_apply_form = CouponApplyForm(
            initial={
                'code': cart.coupon.code,
            }
        )
    else:
        coupon_apply_form = CouponApplyForm()
    if products:
        r = Recommender()
        recommendations = r.suggest_products_for(products, max_length=4)
    return render(
        request=request,
        template_name='cart/detail.html',
        context={
            'cart': cart,
            'recommendations': recommendations,
            'coupon_apply_form': coupon_apply_form,
        }
    )


def experiment(request):
    cart = Cart(request)

    # --- console ---
    console(request.COOKIES)
    # console(request.META)
    # p_dir(request)
    # console(HttpResponse().headers)
    # --- console ---

    return JsonResponse({'status': 'ok'})

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Корзина{% endblock %}

{% block content %}
<h1>Ваша корзина</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Фото</th>
        <th>Товар</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена одной единицы</th>
        <th>Цена вашего количества</th>

    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.photo %}
                {{ product.photo.url }}
                {% else %}
                {% static 'img/no_image.png' %}
                {% endif %}">
            </a>
        </td>
        <td>
            <a href="{{ product.get_absolute_url }}">
                {{ product.name }}
            </a>
        </td>
        <td>
            <form action="{% url 'cart:add_to_cart' product.pk %}" method="POST">{% csrf_token %}
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                &nbsp;<input type="submit" value="Изменить">
            </form>
        </td>
        <td>
            <a href="{% url 'cart:remove_from_cart' product_id=product.pk %}">
                Удалить
            </a>
        </td>
        <td class="num">
            $ {{ item.price }}
        </td>
        <td class="num">
            $ {{ item.total_price }}
        </td>
    </tr>

    {% endwith %}
    {% endfor %}
    {% with coupon=cart.coupon %}
    {% if coupon %}
    <tr class="subtotal">
        <td>Без скидки</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_full_price }}</td>
    </tr>
    <tr>
        <td>
            "{{ coupon.code }}" Купон
            ({{ coupon.discount }}%)
        </td>

        <td colspan="4"></td>
        <td class="num neg">
            - ${{ cart.get_discount|floatformat:"2" }}
        </td>
    </tr>

    {% endif %}
    {% endwith %}
    <tr class="total">
        <td>Итоговая сумма</td>
        <td colspan="4"></td>
        <td class="num">
            $ {{ cart.get_full_price_after_discount|floatformat:"2" }}
        </td>
    </tr>
    </tbody>

</table>

<!--рекомандации -->
{% if recommendations %}
{% include '_inc/recommendations.html' with cart_css='cart' %}
{% endif %}

<!-- купоны -->
<p>Применить купон</p>
<form action="{% url 'coupons:apply' %}" method="post">
    {% csrf_token %}
    {{ coupon_apply_form }}
    <input type="submit" value="Применить">
</form>

<p class="text-right">
    <a href="{% url 'store:list_products' %}" class="button-light">
        Вернуться к покупкам
    </a>&nbsp;
    <a href="{% url 'orders:create_order' %}" class="button">
        Оформить заказ
    </a>
</p>
{% endblock %}