cart/urls.py
from django.urls import path

from cart.views import (
    add_to_cart_view,
    detail_cart_view,
    remove_from_cart_view,
    experiment
)

app_name = 'cart'

urlpatterns = [
    path('', detail_cart_view, name='detail_cart'),
    path('add/<int:product_id>', add_to_cart_view, name='add_to_cart'),
    path('remove/<int:product_id>', remove_from_cart_view, name='remove_from_cart'),
    path('experiment/', experiment, name='experiment'),
]

shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('store.urls', namespace='store')),
]
if settings.DEBUG:
    urlpatterns += static(
        prefix=settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    # django-debug-toolbar
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

templates/_inc/header.html
{% load static %}
<div id="header">
    <a href="/" class="logo">
        <i class="fa fa-coffee fa-2x" aria-hidden="true"></i> &nbsp;&nbsp;
        Магазин приятного застолья</a>
<!--    https://editor.freelogodesign.org/en/logo/edit/67aef9e67e4540cd9c34081fb7aee5f3?template=53196&category=19 -->
</div>
<div id="subheader">
<!--    <img src="{# static 'img/logo.png' #}">-->

    <div class="cart">
        <a href="{% url 'cart:detail_cart' %}">
            <i class="fa fa-shopping-basket fa-2x" aria-hidden="true"></i>
            <strong>({{ cart|length }})</strong>
        </a>
    </div>
</div>

templates/_inc/recommendations.html
{% load static %}
<div class="recommendations {{ cart_css }}">
    <h3>Вместе с этими товарами часто берут</h3>
    {% for product in recommendations %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.photo %}
                {{ product.photo.url }}
                {% else %}
                {% static 'img/no_image.png' %}
                {% endif %}">
        </a>
        <p>
            <a href="{{ product.get_absolute_url }}">
                {{ product.name }} ({{ product.category }})
            </a>
        </p>
    </div>
    {% endfor %}
</div>